---
- name: "Creation du repertoire de generation des fichiers"
  file:
    path: "/home/{{ user }}/{{ server_word_dir }}"
    state: directory
    mode: "u=rwx,g=r,o=r"

- name: "Creation de la clee privee du serveur"
  command: openssl genrsa -out /home/{{ user }}/{{ server_word_dir }}/wstutorialPrivate.key 4096

- name: "Creation de la demande de signature de certificat (CSR)"
  command: openssl req -new -key /home/{{ user }}/{{ server_word_dir }}/wstutorialPrivate.key -out /home/{{ user }}/{{ server_word_dir }}/wstutorial.csr -nodes -subj "/C=US/ST=Ohio/L=Ohio/O=wstutorial/OU=IT/CN=wstutorial.com"    

- name: "Creation d'un certificat auto-signer"
  command: openssl x509 -signkey /home/{{ user }}/{{ server_word_dir }}/wstutorialPrivate.key -in /home/{{ user }}/{{ server_word_dir }}/wstutorial.csr -req -days 365 -out /home/{{ user }}/{{ server_word_dir }}/wstutorial.crt

- name: "Stockage de la cle privee et du certificat auto-signe dans un keystore PKCS12"
  command: openssl pkcs12 -export -out /home/{{ user }}/{{ server_word_dir }}/keystore.p12 -inkey /home/{{ user }}/{{ server_word_dir }}/wstutorialPrivate.key -in /home/{{ user }}/{{ server_word_dir }}/wstutorial.crt -password pass:1234567890
    
- name: "Stockage du certificat d'autorite de confiance dans le truststore ICI le certificat du serveur"
  command: keytool -import -trustcacerts -alias root -file /home/{{ user }}/{{ server_word_dir }}/wstutorial.crt -keystore /home/{{ user }}/{{ server_word_dir }}/truststore.jks -storepass k1234567890 -noprompt